config/routes.rb
MiniAppSurvey::Application.routes.draw do

  root :to => "surveys#index"

  devise_for :users

  resources :users, :only => [:show, :edit, :update]
  
  resources :surveys do 
    member do
      put 'toggle_publish' 
      put 'toggle_watch'
    end
    
    collection do
      get 'watch'
      get 'my'
    end
  end
  
  resources :choices, :only => [:create]
    
end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :question
  has_many   :choices

  def percentage
    self.choices.empty? ? 0 : (self.choices.size.to_f / self.question.total.to_f * 100)
  end
  
end

app/models/choice.rb
# encoding: utf-8

class Choice < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :answer
  
  validates :user,   :presence => true
  validates :answer, :presence => true
  
  # validates_uniqueness_of :user_id, :scope => :answer_id , :message => "Voce já respondeu essa pergunta!" 
  validate :if_responded
   
  private
  
  def if_responded 
    if self.answer_id.present? and self.user_id.present?
      answer = Answer.find self.answer_id
      user = User.find self.user_id
    
      errors.add("choice", "Você já respondeu essa pergunta!") if answer.question.already_responded?(user)
    end
  end

end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :survey
  has_many   :answers, :dependent => :destroy
  has_many   :choices, :dependent => :destroy
  
  accepts_nested_attributes_for :answers, :allow_destroy => true, :reject_if => lambda { |at| at[:content].blank? } 
  
  def already_responded?(user)
    (user.choices.map(&:answer_id) & self.answer_ids).any?
  end
  
  def total
    self.answers.map(&:choice_ids).flatten.compact.count
  end
  
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  
  belongs_to :user
  has_many   :questions, :dependent => :destroy
  has_many   :watches,   :dependent => :destroy
  has_many   :users,     :through   => :watches
  
  accepts_nested_attributes_for :questions, :allow_destroy => true, :reject_if => lambda { |at| at[:content].blank? }
  
  validates :name, :presence => true
  validates :user, :presence => true
  
  scope :published, where(:published => true)

  def self.watching(user)
    includes(:questions).where(:id => user.watches.map(&:survey_id))
  end
  
  def self.my(user)
    user.surveys.includes(:questions)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :surveys, :dependent => :destroy
  has_many :watches
  has_many :choices 
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :avatar

  mount_uploader :avatar, AvatarUploader
end

app/models/watch.rb
class Watch < ActiveRecord::Base
  belongs_to :user
  belongs_to :survey
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/choices_controller.rb
# encoding: utf-8

class ChoicesController < ApplicationController
  before_filter  :authenticate_user!
  
  def create
    @choice = Choice.new params[:choice]
    @choice.user_id = current_user.id
    
    if @choice.save
      redirect_to :back, :notice => "Pesquisa respondida com sucesso."
    else
      redirect_to :back, :alert => "Não foi possível gravar sua resposta. Por favor, tente novamente."
    end
  end
end

app/controllers/surveys_controller.rb
# encoding: utf-8

class SurveysController < ApplicationController
  before_filter  :authenticate_user!, :except => [:index, :show]
  
  def index
    @choice = Choice.new        
    @surveys = Survey.includes(:questions)
  end

  def show
    @survey = Survey.find(params[:id])
    @choice = Choice.new        
    @questions = @survey.questions.includes(:answers) 
  end

  def new
    @survey = Survey.new
    question = @survey.questions.build 
    2.times { question.answers.build }
  end

  def create
    @survey = Survey.new(params[:survey])
    @survey.user_id = current_user.id
    if @survey.save
      redirect_to @survey, :notice => "Pesquisa criada com sucesso."
    else
      render :action => 'new'
    end
  end

  def edit
    @survey = Survey.find(params[:id])
  end

  def update
    @survey = Survey.find(params[:id])
    if @survey.update_attributes(params[:survey])
      redirect_to @survey, :notice  => "Pesquisa atualizada com sucesso."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
  
    redirect_to surveys_url, :notice => "Pesquisa removida com sucesso."
  end
  
  def toggle_publish
    @survey = Survey.find params[:id]
    @survey.update_attribute :published, !@survey.published

    redirect_to :back
  end  
  
  # OPTIMIZE
  def toggle_watch
    @survey = Survey.find params[:id]
    if @survey.watches.map(&:user_id).include? current_user.id
       @survey.watches.where(:user_id => current_user.id).first.destroy 
    else
      @survey.watches.build :user_id => current_user.id
      @survey.save
    end
    
    redirect_to :back
  end
  
  def watch
    @choice  = Choice.new
    @surveys = Survey.watching current_user
    @title   = "Pesquisas que acompanho(watch)"
    render :index
  end
  
  def my
    @choice  = Choice.new
    @surveys = Survey.my current_user
    @title   = "Minha pesquisas"
    
    render :index
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find current_user.id
  end

  def update
    @user = User.find current_user.id
    @user.update_attributes params[:user]
    redirect_to @user, :notice => "Perfil atualizado com sucesso."
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.input(:_destroy, :as => :hidden) + link_to_function(name, "remove_fields(this)", :class => "remove_field")
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, raw("add_fields(this, '#{association}', '#{escape_javascript(fields)}')"), :class => 'add_field')
  end
  
  def show_survey(survey)
    if current_user
			survey.published? or survey.user_id.eql? current_user.id
		else
			survey.published?
		end
  end
  
  def title(page_title)
    content_for :title do
    	page_title
    end
  end  
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= yield(:title).present? ? yield(:title) : "Pesquisas" %> </title>
	  <%= stylesheet_link_tag :all %>
	  <%= javascript_include_tag :defaults %>
	  <%= csrf_meta_tag %>
	</head>
	<body>
		<div id="main">
			<div id="header">
				<h1><%= link_to "MiniApp Surveys", root_path, :title => "Todas as pesquisas" %></h1>
				<ul>
				<% if user_signed_in? %>
				  <li>
				   	<%= link_to(current_user.name.present? ? current_user.name : current_user.email, user_path(current_user)) %> |
				 		<%= link_to "Sair", destroy_user_session_path, :method => :delete %>        
				  </li>	
				<% else %>
				  <li>
				  <%= link_to "Entrar", new_user_session_path %> | <%= link_to "Registrar-se", new_user_registration_path  %> 
				  </li>
				<% end %>
				</ul>
			</div>
			<div id="content">
				<% if current_user %>
				<div id="menu">
					<%= link_to "Criar pesquisa", new_survey_path %>
					<ul>
						<li><%= link_to "Minhas pesquisas", my_surveys_path %></li>
						<li><%= link_to "Pesquisas que acompanho", watch_surveys_path %></li>
					</ul>
				</div>
				<% end %>
				
				<h3 id="title"><%= yield(:title).present? ? yield(:title) : "Pesquisas" %></h3>
				
				<% if notice %>
					<p class="notice"><%= notice %></p>
				<% end %>
				<% if alert %>
					<p class="alert"><%= alert %></p>
				<% end %>
								
				<%= yield %>
				
			</div>
		</div>
	</body>
</html>

app/views/surveys/_answer_fields.html.erb
<div class="fields">
	<div class="question-field">
		<%= f.input :content, :label => "Resposta", :wrapper_html => { :class => 'answer' } %>
		<%= link_to_remove_fields "remover", f %>
	</div>
</div>

app/views/surveys/_form.html.erb
<%= simple_form_for @survey  do |f| %>
	<%= f.input :name, :label => "Nome" %>
  <%= f.input :description, :input_html => { :rows => 4}, :label => "Descrição" %>
	<%= f.simple_fields_for :questions do |builder| %>
		<%= render 'question_fields', :f => builder %>
	<% end %>
	<div class="add-question">
		<%= link_to_add_fields "Adicionar pergunta", f, :questions %>
  </div>
	<%= f.submit btn_form %>
<% end %>

app/views/surveys/_question_fields.html.erb
<div class="fields">
	<div class="question-field">
		<%= f.input :content, :label => "Pergunta", :wrapper_html => { :class => 'question' } %>
		<%= link_to_remove_fields "remover", f %>
	</div>
	<%= f.simple_fields_for :answers do |builder| %>
		<%= render 'answer_fields', :f => builder %>
	<% end %>
	<div class="add-answer">
		<%= link_to_add_fields "Adicionar resposta", f, :answers %>
	</div>
</div>

app/views/surveys/_survey.html.erb
<% if show_survey(survey) %>
			<div class="surveys">
		    <h3><%= link_to survey.name.titleize , survey %></h3> 
		    <%= link_to(survey.watches.map(&:user_id).include?(current_user.id) ? "unwatch" : "watch",
				 						 toggle_watch_survey_path(survey), :method => :put, :class => "watch_unwatch") if user_signed_in?  %>
				<small><b>Descrição:</b>&nbsp;<%= survey.description.titleize %></small>
				
				<%= render 'survey_links', :survey => survey %>
				
				<h4>Pergunta(s) dessa pesquisa</h4>
								
				<% survey.questions.each do |question| %>
		      <ul class="questions">
		        <li>
							<strong><%= question.content %></strong>(<%= pluralize(question.total, "Respostas") %>)
						</li>
		        <% if current_user and not question.already_responded?(current_user) %>
		          <%= form_for @choice do |f| %>
		            <% question.answers.each do |answer| %>
		              <li><%= f.radio_button :answer_id, answer.id %>&nbsp;&nbsp;<%= answer.content.titleize %></li>
		            <% end %>
		            <%= f.submit "Responder" %>
		          <% end %>
		        <% else %>
							<% question.answers.each do |answer| %>
								<li>
			            <span style="display: block;">
			              <%= answer.content.titleize %>
			            </span>
			            <span class="bar">
										<span style="width:<%= sprintf("%2.f%", answer.percentage) %>;"></span>
									</span>
			            <span class="percent"><%= sprintf("%2.f%", answer.percentage) %></span>
			         </li>
			        <% end %>
		        <% end %>
		      </ul>
		    <% end  %>
		  </div>
		<% end %>

app/views/surveys/_survey_links.html.erb
<% if user_signed_in? %>
	<% if survey.user_id.eql? current_user.id %>
		<div class="manager">
		<%= link_to 'Editar', edit_survey_path(survey) %> |
	  <%= link_to 'Excluir', survey, :confirm => 'Tem certeza que deseja excluir?', :method => :delete %> |
		<%= link_to  survey.published? ? "Despublicar" : "Publicar", toggle_publish_survey_path(survey), :method => :put  %>
		<% if survey.watches.any? %>
			<h4>Pessoas que acompanham essa pesquisa</h4>
			<ul class="watches">
				<% survey.watches.each do |watch| %>
					<li>
						<%= link_to image_tag(watch.user.avatar.url(:mini), :alt => watch.user.name),
						 user_path(watch.user), :title => watch.user.name %>
					</li>
				<% end %>
			</ul>
		<% end %>
		</div>
	<% end %>
<% end %>

app/views/surveys/edit.html.erb
<% title "Editar pesquisa: #{ @survey.name }" %>

<div class="survey-form">
	<%= render 'form', :btn_form => "Atualizar Pesquisa" %>
</div>

<p>
  <%= link_to "Show", @survey %> |
  <%= link_to "View All", surveys_path %>
</p>

app/views/surveys/index.html.erb
<%= title(@title) %>

<% if @surveys.any? %>
	<% @surveys.reverse.each do |survey| %>
	  <%= render 'survey', :survey => survey %>
	<% end %>
<% else %>
	<div class="surveys">Nenhuma pesquisa.</div>
<% end %>

app/views/surveys/new.html.erb
<% title("Criar pesquisa") %>

<div class="survey-form">
	<%= render 'form', :btn_form => "Criar Pesquisa" %>
</div>

app/views/surveys/show.html.erb
<%= title("Pesquisa: #{@survey.name}") %>

<%= render 'survey', :survey => @survey %>

app/views/users/edit.html.erb
<% title("Editar usuário") %>

<div class="user">
	<%= simple_form_for @user, :html => { :multipart => true} do |f| %>
	    <%= f.input :name,  :label => "Nome" %>
	    <%= f.input :email, :lavel => "E-mail" %>
	    <%= f.input :avatar %>
	    <%= f.button :submit, "Atualizar" %>
	<% end %>

	<br/>
	<p>
		<%= link_to "Alterar senha", edit_user_registration_path %> |
		<%= link_to "Deletar conta", registration_path(@user),
		 	:confirm => "Tem certeza que deseja remover sua conta?", :method => :delete %> |
			<%= link_to "Voltar", :back %>
	</p>
</div>

app/views/users/show.html.erb
<% title("Usuário") %>

<div class="user">
	<p><%= image_tag @user.avatar.url(:thumb) %></p>
	<p><b>Nome:</b> <%= @user.name %></p>
	<p><b>E-mail:</b> <%= @user.email %></p>

	<br/>
	<% if current_user.id.eql? @user.id %>
		<p><%= link_to "Editar", edit_user_path(@user) %> | <%= link_to "Voltar", :back %></p>
	<% end %>
</div>